"""empty message

Revision ID: 81bceb8d4cc8
Revises: aeb985d9f8a0
Create Date: 2018-04-09 15:16:20.572562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bceb8d4cc8'
down_revision = 'aeb985d9f8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('internal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'internal')
    # ### end Alembic commands ###
