"""empty message

Revision ID: 87c5547f76b3
Revises: f77bbe0e5104
Create Date: 2018-05-16 10:40:23.837956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c5547f76b3'
down_revision = 'f77bbe0e5104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_message_cancelled'),
                    'message', ['cancelled'], unique=False)
    op.create_index(op.f('ix_message_confirmed'),
                    'message', ['confirmed'], unique=False)
    op.create_index(op.f('ix_message_receiver'),
                    'message', ['receiver'], unique=False)
    op.create_index(op.f('ix_message_receiver_type'),
                    'message', ['receiver_type'], unique=False)
    op.create_index(op.f('ix_message_retrieved'),
                    'message', ['retrieved'], unique=False)
    op.create_index(op.f('ix_message_sender'),
                    'message', ['sender'], unique=False)
    op.create_index(op.f('ix_message_sender_type'),
                    'message', ['sender_type'], unique=False)
    op.create_index('message_type_index', 'message', [
                    'message_type_id'], unique=False)
    op.alter_column('message_type', 'created_by_',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    existing_server_default=sa.text("'sys'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_type', 'created_by_',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    existing_server_default=sa.text("'sys'::character varying"))
    op.drop_index('message_type_index', table_name='message')
    op.drop_index(op.f('ix_message_sender_type'), table_name='message')
    op.drop_index(op.f('ix_message_sender'), table_name='message')
    op.drop_index(op.f('ix_message_retrieved'), table_name='message')
    op.drop_index(op.f('ix_message_receiver_type'), table_name='message')
    op.drop_index(op.f('ix_message_receiver'), table_name='message')
    op.drop_index(op.f('ix_message_confirmed'), table_name='message')
    op.drop_index(op.f('ix_message_cancelled'), table_name='message')
    # ### end Alembic commands ###
