"""empty message

Revision ID: be834046f941
Revises: e9f663477d07
Create Date: 2018-02-16 16:03:26.092956

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'be834046f941'
down_revision = 'e9f663477d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    message_type_table = op.create_table(
        'message_type',
        sa.Column('uuid', sa.String(
            length=36), nullable=False),
        sa.Column(
            'created', sa.DateTime(), nullable=False),
        sa.Column(
            'modified', sa.DateTime(), nullable=False),
        sa.Column(
            'value', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('value')
    )

    op.drop_column('message', 'subject')
    op.add_column('message', sa.Column(
        'message_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'message_type', [
                          'message_type_id'], ['value'])
    # ### end Alembic commands ###
    data = [
        {
            "uuid": "General",
            "created": datetime.utcnow(),
            "modified": datetime.utcnow(),
            "value": 0,
        },
        {
            "uuid": "Dosage",
            "created": datetime.utcnow(),
            "modified": datetime.utcnow(),
            "value": 1,
        },
        {
            "uuid": "Dietary",
            "created": datetime.utcnow(),
            "modified": datetime.utcnow(),
            "value": 2,
        },
        {
            "uuid": "Callback",
            "created": datetime.utcnow(),
            "modified": datetime.utcnow(),
            "value": 3,
        },
        {
            "uuid": "Feedback",
            "created": datetime.utcnow(),
            "modified": datetime.utcnow(),
            "value": 4,
        },
    ]
    op.bulk_insert(message_type_table, data)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'message_type_id')
    op.drop_table('message_type')
    # ### end Alembic commands ###
