"""empty message

Revision ID: ee8eecdaa155
Revises: 61b7606dfac7
Create Date: 2018-03-08 10:30:17.722981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8eecdaa155'
down_revision = '61b7606dfac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('confirmed_tz', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('retrieved_tz', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'retrieved_tz')
    op.drop_column('message', 'confirmed_tz')
    # ### end Alembic commands ###
